services:
  purpur-bot:
    build:
      context: ../
      dockerfile: container/Dockerfile
    volumes:
      - ./../.env:/app/.env
      - ./../container_data:/app/data
    ports:
      - "8000:8000"
